import { HiUserGroup } from 'react-icons/hi';
import {
  FiUser,
  FiEdit2,
  FiTrash2,
  FiHome,
  FiSettings,
  FiLogIn,
  FiLogOut,
  FiPlus,
  FiMinus,
  FiCheck,
  FiX,
  FiMenu,
  FiSearch,
  FiBook,
  FiClock,
  FiAward,
  FiHelpCircle,
  FiAlertCircle,
  FiBarChart,
  FiList,
  FiArrowRight,
  FiArrowLeft,
  FiSun,
  FiMoon,
} from 'react-icons/fi';
import { RiShuffleLine } from 'react-icons/ri';
import { MdExpandMore, MdQuiz, MdTimer, MdLeaderboard, MdPlayArrow } from 'react-icons/md';
import {
  BsQuestionCircle,
  BsCheckCircle,
  BsTrophy,
  BsXCircle,
  BsBookmark,
  BsBookmarkFill,
} from 'react-icons/bs';
import { IconName } from './types';
import { IconType } from 'react-icons';

export const icons: Record<IconName, IconType> = {
  group: HiUserGroup,
  person: FiUser,
  shuffle: RiShuffleLine,
  edit: FiEdit2,
  delete: FiTrash2,
  expandMore: MdExpandMore,
  bookmarkFilled: BsBookmarkFill,

  home: FiHome,
  settings: FiSettings,
  login: FiLogIn,
  logout: FiLogOut,
  add: FiPlus,
  remove: FiMinus,
  check: FiCheck,
  close: FiX,
  menu: FiMenu,
  search: FiSearch,
  book: FiBook,
  timer: FiClock,
  award: FiAward,
  help: FiHelpCircle,
  alert: FiAlertCircle,
  chart: FiBarChart,
  list: FiList,
  question: BsQuestionCircle,
  correct: BsCheckCircle,
  wrong: BsXCircle,
  trophy: BsTrophy,
  bookmark: BsBookmark,
  quiz: MdQuiz,
  countdown: MdTimer,
  leaderboard: MdLeaderboard,
  play: MdPlayArrow,
  arrowRight: FiArrowRight,
  arrowLeft: FiArrowLeft,
  sun: FiSun,
  moon: FiMoon,
};
