export type IconName =
  | 'group'
  | 'person'
  | 'shuffle'
  | 'edit'
  | 'delete'
  | 'expandMore'
  | 'home'
  | 'settings'
  | 'login'
  | 'logout'
  | 'add'
  | 'remove'
  | 'check'
  | 'close'
  | 'menu'
  | 'search'
  | 'book'
  | 'timer'
  | 'award'
  | 'help'
  | 'alert'
  | 'chart'
  | 'list'
  | 'question'
  | 'trophy'
  | 'play'
  | 'arrowRight'
  | 'arrowLeft'
  | 'correct'
  | 'wrong'
  | 'bookmark'
  | 'bookmarkFilled'
  | 'leaderboard'
  | 'quiz'
  | 'countdown'
  | 'sun'
  | 'moon'
  | 'dashboard'
  | 'atom'
  | 'scroll'
  | 'globe'
  | 'film'
  | 'soccerBall'
  | 'puzzle'
  | 'counter'
  | 'percentage'
  | 'star';

export interface IconProps {
  name: IconName;
  size?: 'small' | 'medium' | 'large' | 'xs';
  color?: string;
  className?: string;
  style?: React.CSSProperties;
}
