# Generated by Django 4.2.1 on 2025-05-10 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0002_remove_user_user_name_alter_quizsession_user_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="question",
            name="answer_options",
            field=models.JSONField(default=list),
        ),
    ]
