# Generated by Django 4.2.1 on 2025-05-13 18:22

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0004_alter_llmgenerationtask_user_alter_quizsession_user_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="llmgenerationtask",
            name="user",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="generation_tasks",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="quiz.category",
            ),
        ),
        migrations.AlterField(
            model_name="question",
            name="difficulty",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="questions",
                to="quiz.difficultylevel",
            ),
        ),
        migrations.AlterField(
            model_name="quizsessionquestion",
            name="question",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="session_answers",
                to="quiz.question",
            ),
        ),
    ]
