# Generated by Django 4.2.1 on 2025-05-16 18:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0006_alter_llmgenerationtask_category_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="GroupPlayer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("score", models.IntegerField(default=0)),
                (
                    "quiz_session",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="group_players",
                        to="quiz.quizsession",
                    ),
                ),
            ],
        ),
    ]
