# Generated by Django 4.2.1 on 2025-05-16 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0007_groupplayer"),
    ]

    operations = [
        migrations.AddField(
            model_name="quizsession",
            name="is_group_session",
            field=models.BooleanField(default=False),
        ),
    ]
