# Generated by Django 4.2.1 on 2025-05-16 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0008_quizsession_is_group_session"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplayer",
            name="errors",
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
