# Generated by Django 4.2.1 on 2025-06-10 01:40

from django.db import migrations

def set_categories(apps, schema_editor):
    Category = apps.get_model("quiz", "Category")
    mapping = {
        1: "Science",
        2: "History",
        3: "Geography",
        4: "Sports",
        5: "Movies",
        6: "Trivia",
    }
    for pk, name in mapping.items():
        Category.objects.update_or_create(id=pk, defaults={"name": name})


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0010_alter_category_options_alter_category_name_and_more"),
    ]

    operations = [
        migrations.RunPython(set_categories),
    ]
