# Generated by Django 4.2.1 on 2025-06-24 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0011_lock_categories"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplayer",
            name="answers",
            field=models.JSONField(default=list),
        ),
    ]
