# Generated by Django 4.2.1 on 2025-06-25 06:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("quiz", "0012_groupplayer_answers"),
    ]

    operations = [
        migrations.AddField(
            model_name="groupplayer",
            name="correct_answers",
            field=models.JSONField(default=dict),
        ),
    ]
